version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  intermediary-service:
    build:
      context: .
      dockerfile: ./apps/intermediary-service/Dockerfile
      target: development
    command: npm run start:dev intermediary-service
    hostname: intermediary-service
    container_name: intermediary-service
    ports:
      - 3000:3000
    volumes:
      - ./apps/intermediary-service/src:/usr/src/app

  order-service:
    build:
      context: .
      dockerfile: ./apps/order-service/Dockerfile
      target: development
    command: npm run start:dev order-service
    hostname: order-service
    container_name: order-service
    volumes:
      - ./apps/order-service/src:/usr/src/app

  inventory-service:
    build:
      context: .
      dockerfile: ./apps/inventory-service/Dockerfile
      target: development
    command: npm run start:dev inventory-service
    hostname: inventory-service
    container_name: inventory-service
    volumes:
      - ./apps/inventory-service/src:/usr/src/app
